id: ABB0754A5
title: Long Life Prayer for Mayum Tsering Wangmo
type: translation
source_metadata:
  languages:
  - en
  - de
  - es
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-03-01 00:45:01.879447
  last_modified_at: 2022-03-01 00:45:01.879454
